version: '3.9'
services:
  core_api:
    container_name: flaskapi
    build:
      context: .
    ports:
      - "5000"
    volumes:
      - ./:/app
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always

  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg12
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
