version: '3.9'
services:
  core_api:
    container_name: flaskapi
    build:
      context: .
    ports:
      - 3000:5000
    restart: always

    depends_on:
      - timescaledb

  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=timescaledb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
