version: '3.4'
services:
  core_api:
    build: .
    container_name: "books_timescale_api"
    image: "books_timescale_api:latest"
    ports:
      - "8080:8080"
    volumes:
      - ./Books/:/Books
