version: '3.9'
services:

  app:
    container_name: app-flask
    build:
      context: app/
    ports:
      - "5000:5000"
    restart: always

  prometheus:
    container_name: prometheus-svc
    image: prom/prometheus
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana-data:/grafana
    ports:
      - '3000:3000'
