global:
  scrape_interval:     5s
  evaluation_interval: 30s
scrape_configs:
  - job_name: my-application
    honor_labels: true
    static_configs:
    - targets: ['app-flask:5000']
    
  - job_name: prometheus
    static_configs:
    - targets: ['localhost:9090']