version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  app_docker:
    build:
      context: .
    ports:
      - "3000:5000"
    volumes:
      - ./:/app
    restart: always

